name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to NETMouse projects! We hope that you like our company. :)'
        pr-message: 'Welcome to NETMouse projects! We hope that you like our company. :)'
