name: Milestone-Labeler
on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: damccorm/tag-ur-it@master
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: "./MilestoneIssueRules.yml"
